# Generated by Django 5.1.4 on 2026-03-17 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testando', '0002_produto_estoque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pedidoitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
    ]
