# Generated by Django 5.1.4 on 2026-03-18 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testando', '0004_funcionario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Produtos', to='testando.tipo'),
        ),
    ]
