# Generated by Django 5.1.4 on 2026-03-18 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testando', '0005_alter_produto_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='testando.produto'),
        ),
        migrations.AlterField(
            model_name='pedidoitem',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testando.produto'),
        ),
    ]
