# Generated by Django 5.1.4 on 2026-03-18 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testando', '0006_alter_estoque_produto_alter_pedidoitem_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='tipo',
            field=models.CharField(choices=[('admin', 'Super Funcionário (Admin)'), ('comum', 'Funcionário Padrão')], default='comum', help_text='Define o nível de acesso no sistema', max_length=10),
        ),
    ]
